class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Money Pilot',
      'total_balance': 'Total Balance',
      'income': 'Income',
      'expense': 'Expense',
      'recent_transactions': 'Recent Transactions',
      'speak': 'Speak',
      'add_income': 'Add Income',
      'add_expense': 'Add Expense',
      'description': 'Description',
      'category': 'Category',
      'date': 'Date',
      'save_transaction': 'Save Transaction',
      'no_transactions': 'No transactions yet.\nAdd one!',
      'manual_input_income': 'Add Income',
      'manual_input_expense': 'Add Expense',
      'enter_amount': 'Enter amount',
      'enter_description': 'Enter description',
      'hint_salary': 'e.g. Salary',
      'hint_grocery': 'e.g. Grocery',
      'other': 'Other',
      'food': 'Food',
      'transport': 'Transport',
      'shopping': 'Shopping',
      'bills': 'Bills',
      'entertainment': 'Entertainment',
      'health': 'Health',
      'salary': 'Salary',
      'freelance': 'Freelance',
      'business': 'Business',
      'gift': 'Gift',
      'settings_title': 'Settings',
      'api_key_label': 'Gemini API Key',
      'api_key_hint': 'Enter your API Key here',
      'save_key': 'Save Key',
      'key_saved': 'API Key Saved Successfully',
      'backup_restore': 'Backup & Restore',
      'change_password': 'Change Password',
      'configure_api': 'Configure Gemini API',
      'coming_soon': 'Coming Soon',
      'get_api_key': 'Get API Key',
      'test_api': 'Test API',
      'test_success': 'Connection Successful!',
      'test_fail': 'Connection Failed. Check Key.',
      'voice_settings': 'Voice Input Settings',
      'privacy_policy': 'Privacy Policy',
      'about': 'About',
      'developer': 'Developer',
      'version': 'Version',
      'see_all': 'See All',
      'expenses_by_category': 'Expenses by Category',
      'all_transactions': 'All Transactions',
      'spending_trend': 'Spending Trend',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'daily_avg': 'Daily Avg',
      'max_spend': 'Max Spend',
      'bonus': 'Bonus',
      'remaining_balance': 'Remaining',
      'this_month_balance': 'This Month Balance',
      'loans': 'Loans',
      'given': 'Given',
      'taken': 'Taken',
      'settle': 'Settle',
      'total_given': 'Total Given',
      'total_taken': 'Total Taken',
      'add_loan': 'Add Loan',
      'ai_insights': 'AI Insights',
      'analyze': 'Analyze',
      'good_job': 'Good Job',
      'tips': 'Smart Tip',
      'analyzing': 'Analyzing...',
      'notifications': 'Notifications',
      'no_notifications': 'No notifications',
      'mark_read': 'Mark as read',
      'delete': 'Delete',
      'budget_alert': 'Budget Alert',
      'loan_reminder': 'Loan Reminder',

      // New Keys for Filters & UI Overhaul
      'search_hint': 'Search transactions...',
      'quick_select': 'Quick Select',
      'filters': 'Filters',
      'reset_all': 'Reset All',
      'date_range': 'Date Range',
      'today': 'Today',
      'last_3_months': 'Last 3 Months',
      'select_custom_range': 'Select Custom Range',
      'apply_filters': 'Apply Filters',
      'filtered_results': 'Filtered Results',
      'no_matching_results': 'No matching results',
      'clear_filters': 'Clear Filters',
      'transaction_type': 'Transaction Type',
      'edit_income': 'Edit Income',
      'edit_expense': 'Edit Expense',

      // Voice Processing
      'processing': 'Processing...',
      'could_not_understand': 'Could not understand. Try again.',
      'transaction_added': 'Transaction Added!',
      'api_limit_reached': 'API Limit Reached. Please wait.',
      'api_key_missing': 'API Key missing. Check Settings.',

      // Extended Categories
      'dining': 'Dining',
      'groceries': 'Groceries',
      'fuel': 'Fuel',
      'clothing': 'Clothing',
      'electronics': 'Electronics',
      'rent': 'Rent',
      'utilities': 'Utilities',
      'movies': 'Movies',
      'medicine': 'Medicine',
      'education': 'Education',
      'tuition': 'Tuition',
      'travel': 'Travel',
      'investment': 'Investment',
      'loan_recovery': 'Loan Recovery',
      'loan_repayment': 'Loan Repayment',
      'loan_settled_msg': 'Loan settled successfully!',
      'loan_no_active': 'No active loans',
      'review_transactions': 'Review Transactions',
      'close': 'Close',
    },
    'bn': {
      'app_title': 'মানি পাইলট',
      'total_balance': 'মোট ব্যালেন্স',
      'income': 'আয়',
      'expense': 'ব্যয়',
      'recent_transactions': 'সাম্প্রতিক লেনদেন',
      'speak': 'কথা বলুন',
      'add_income': 'আয় যোগ করুন',
      'add_expense': 'ব্যয় যোগ করুন',
      'description': 'বিবরণ',
      'category': 'ধরণ',
      'date': 'তারিখ',
      'save_transaction': 'লেনদেন সেভ করুন',
      'no_transactions': 'কোন লেনদেন নেই।\nএকটি যোগ করুন!',
      'manual_input_income': 'আয় যোগ করুন',
      'manual_input_expense': 'ব্যয় যোগ করুন',
      'enter_amount': 'টাকার পরিমাণ দিন',
      'enter_description': 'বিবরণ দিন',
      'hint_salary': 'যেমন: বেতন',
      'hint_grocery': 'যেমন: বাজার',
      'other': 'অন্যান্য',
      'food': 'খাবার',
      'transport': 'যাতায়াত',
      'shopping': 'কেনাকাটা',
      'bills': 'বিল',
      'entertainment': 'বিনোদন',
      'health': 'স্বাস্থ্য',
      'salary': 'বেতন',
      'freelance': 'ফ্রিল্যান্সিং',
      'business': 'ব্যবসা',
      'gift': 'উপহার',
      'settings_title': 'সেটিংস',
      'api_key_label': 'জেমিনি এপিআই কি',
      'api_key_hint': 'আপনার এপিআই কি এখানে দিন',
      'save_key': 'কি সেভ করুন',
      'key_saved': 'এপিআই কি সফলভাবে সেভ করা হয়েছে',
      'backup_restore': 'ব্যাকআপ এবং রিস্টোর',
      'change_password': 'পাসওয়ার্ড পরিবর্তন',
      'configure_api': 'জেমিনি এপিআই কনফিগার',
      'coming_soon': 'শীঘ্রই আসছে',
      'get_api_key': 'এপিআই কি সংগ্রহ করুন',
      'test_api': 'এপিআই টেস্ট করুন',
      'test_success': 'সংযোগ সফল হয়েছে!',
      'test_fail': 'সংযোগ ব্যর্থ হয়েছে। কি চেক করুন।',
      'voice_settings': 'ভয়েস ইনপুট সেটিংস',
      'privacy_policy': 'গোপনীয়তা নীতি',
      'about': 'সম্পর্কে',
      'developer': 'ডেভেলপার',
      'version': 'ভার্সন',
      'see_all': 'সব দেখুন',
      'expenses_by_category': 'খরচের খাতসমূহ',
      'all_transactions': 'সকল লেনদেন',
      'spending_trend': 'খরচের প্রবণতা',
      'this_week': 'এই সপ্তাহ',
      'this_month': 'এই মাস',
      'daily_avg': 'দৈনিক গড়',
      'max_spend': 'সর্বোচ্চ খরচ',
      'bonus': 'বোনাস',
      'remaining_balance': 'অবশিষ্ট',
      'this_month_balance': 'এই মাসের ব্যালেন্স',
      'loans': 'ঋণ',
      'given': 'পাওনা',
      'taken': 'দেনা',
      'settle': 'শোধ',
      'total_given': 'মোট পাওনা',
      'total_taken': 'মোট দেনা',
      'add_loan': 'ঋণ যোগ করুন',
      'ai_insights': 'এআই পরামর্শ',
      'analyze': 'বিশ্লেষণ করুন',
      'good_job': 'ভালো দিক',
      'tips': 'পরামর্শ',
      'analyzing': 'বিশ্লেষণ চলছে...',
      'notifications': 'বিজ্ঞপ্তি',
      'no_notifications': 'কোন বিজ্ঞপ্তি নেই',
      'mark_read': 'পড়া হয়েছে',
      'delete': 'মুছুন',
      'budget_alert': 'বাজেট সতর্কতা',
      'loan_reminder': 'ঋণ মনে করিয়ে দিন',

      // New Keys for Filters & UI Overhaul
      'search_hint': 'লেনদেন খুঁজুন...',
      'quick_select': 'দ্রুত নির্বাচন',
      'filters': 'ফিল্টার',
      'reset_all': 'সব মুছুন',
      'date_range': 'তারিখের পরিসীমা',
      'today': 'আজ',
      'last_3_months': 'গত ৩ মাস',
      'select_custom_range': 'পছন্দমতো তারিখ নির্বাচন করুন',
      'apply_filters': 'ফিল্টার প্রয়োগ করুন',
      'filtered_results': 'ফিল্টার করা ফলাফল',
      'no_matching_results': 'কোনো মিল পাওয়া যায়নি',
      'clear_filters': 'ফিল্টার মুছুন',
      'transaction_type': 'লেনদেনের ধরন',
      'edit_income': 'আয় সংশোধন',
      'edit_expense': 'ব্যয় সংশোধন',

      // Voice Processing
      'processing': 'প্রক্রিয়াধীন...',
      'could_not_understand': 'বুঝতে পারিনি। আবার চেষ্টা করুন।',
      'transaction_added': 'লেনদেন যোগ করা হয়েছে!',
      'api_limit_reached': 'এপিআই সীমা শেষ। কিছুক্ষণ পর চেষ্টা করুন।',
      'api_key_missing': 'এপিআই কি পাওয়া যায়নি। সেটিংস দেখুন।',

      // Extended Categories
      'dining': 'ডাইনিং',
      'groceries': 'মুদি বাজার',
      'fuel': 'জ্বালানি',
      'clothing': 'পোশাক',
      'electronics': 'ইলেকট্রনিক্স',
      'rent': 'ভাড়া',
      'utilities': 'ইউটিলিটি বিল',
      'movies': 'চলচ্চিত্র',
      'medicine': 'ওষুধ',
      'education': 'শিক্ষা',
      'tuition': 'টিউশন',
      'travel': 'ভ্রমণ',
      'investment': 'বিনিয়োগ',
      'loan_recovery': 'ঋণ আদায়',
      'loan_repayment': 'ঋণ পরিশোধ',
      'loan_settled_msg': 'ঋণ সফলভাবে শোধ করা হয়েছে!',
      'loan_no_active': 'বর্তমানে কোনো ঋণ নেই',
      'review_transactions': 'লেনদেন পর্যালোচনা',
      'close': 'বন্ধ করুন',
    },
  };

  static String get(String lang, String key) {
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
  
  // Helper to translate categories
  static String getCategory(String lang, String category) {
    final key = category.toLowerCase();
    return _localizedValues[lang]?[key] ?? category;
  }
}
