class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Money Pilot',
      'total_balance': 'Total Balance',
      'income': 'Income',
      'expense': 'Expense',
      'recent_transactions': 'Recent Transactions',
      'speak': 'Speak',
      'add_income': 'Add Income',
      'add_expense': 'Add Expense',
      'description': 'Description',
      'category': 'Category',
      'date': 'Date',
      'save_transaction': 'Save Transaction',
      'no_transactions': 'No transactions yet.\nAdd one!',
      'manual_input_income': 'Add Income',
      'manual_input_expense': 'Add Expense',
      'enter_amount': 'Enter amount',
      'enter_description': 'Enter description',
      'hint_salary': 'e.g. Salary',
      'hint_grocery': 'e.g. Grocery',
      'other': 'Other',
      'food': 'Food',
      'transport': 'Transport',
      'shopping': 'Shopping',
      'bills': 'Bills',
      'entertainment': 'Entertainment',
      'health': 'Health',
      'salary': 'Salary',
      'freelance': 'Freelance',
      'business': 'Business',
      'gift': 'Gift',
      'settings_title': 'Settings',
      'api_key_label': 'Gemini API Key',
      'api_key_hint': 'Enter your API Key here',
      'save_key': 'Save Key',
      'key_saved': 'API Key Saved Successfully',
      'backup_restore': 'Backup & Restore',
      'change_password': 'Change Password',
      'configure_api': 'Configure Gemini API',
      'coming_soon': 'Coming Soon',
      'get_api_key': 'Get API Key',
      'test_api': 'Test API',
      'test_success': 'Connection Successful!',
      'test_fail': 'Connection Failed. Check Key.',
    },
    'bn': {
      'app_title': 'মানি পাইলট',
      'total_balance': 'মোট ব্যালেন্স',
      'income': 'আয়',
      'expense': 'ব্যয়',
      'recent_transactions': 'সাম্প্রতিক লেনদেন',
      'speak': 'কথা বলুন',
      'add_income': 'আয় যোগ করুন',
      'add_expense': 'ব্যয় যোগ করুন',
      'description': 'বিবরণ',
      'category': 'ধরণ',
      'date': 'তারিখ',
      'save_transaction': 'লেনদেন সেভ করুন',
      'no_transactions': 'কোন লেনদেন নেই।\nএকটি যোগ করুন!',
      'manual_input_income': 'আয় যোগ করুন',
      'manual_input_expense': 'ব্যয় যোগ করুন',
      'enter_amount': 'টাকার পরিমাণ দিন',
      'enter_description': 'বিবরণ দিন',
      'hint_salary': 'যেমন: বেতন',
      'hint_grocery': 'যেমন: বাজার',
      'other': 'অন্যান্য',
      'food': 'খাবার',
      'transport': 'যাতায়াত',
      'shopping': 'কেনাকাটা',
      'bills': 'বিল',
      'entertainment': 'বিনোদন',
      'health': 'স্বাস্থ্য',
      'salary': 'বেতন',
      'freelance': 'ফ্রিল্যান্সিং',
      'business': 'ব্যবসা',
      'gift': 'উপহার',
      'settings_title': 'সেটিংস',
      'api_key_label': 'জেমিনি এপিআই কি',
      'api_key_hint': 'আপনার এপিআই কি এখানে দিন',
      'save_key': 'কি সেভ করুন',
      'key_saved': 'এপিআই কি সফলভাবে সেভ করা হয়েছে',
      'backup_restore': 'ব্যাকআপ এবং রিস্টোর',
      'change_password': 'পাসওয়ার্ড পরিবর্তন',
      'configure_api': 'জেমিনি এপিআই কনফিগার',
      'coming_soon': 'শীঘ্রই আসছে',
      'get_api_key': 'এপিআই কি সংগ্রহ করুন',
      'test_api': 'এপিআই টেস্ট করুন',
      'test_success': 'সংযোগ সফল হয়েছে!',
      'test_fail': 'সংযোগ ব্যর্থ হয়েছে। কি চেক করুন।',
    },
  };

  static String get(String lang, String key) {
    return _localizedValues[lang]?[key] ?? _localizedValues['en']![key]!;
  }
  
  // Helper to translate categories
  static String getCategory(String lang, String category) {
    // Attempt to find a translation for the category, fallback to original if not found
    // This assumes category names in DB match the keys or are English by default
    final key = category.toLowerCase();
    return _localizedValues[lang]?[key] ?? category;
  }
}
